name: Update Twilio Credentials

on:
  schedule:
      - cron: "0 0 * * 1"
        workflow_dispatch:

        jobs:
          update-credentials:
              runs-on: ubuntu-latest

                  steps:
                      - name: Checkout repository
                            uses: actions/checkout@v2

                                - name: Set up Python
                                      uses: actions/setup-python@v2
                                            with:
                                                    python-version: '3.x'

                                                        - name: Install dependencies
                                                              run: |
                                                                      python -m pip install --upgrade pip
                                                                              pip install requests

                                                                                  - name: Run script to update Twilio credentials
                                                                                        env:
                                                                                                TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
                                                                                                        TWILIO_AUTH_TOKEN: ${{ secrets.TWILIO_AUTH_TOKEN }}
                                                                                                              run: |
                                                                                                                      python script/update_twilio_credentials.py
                                                                                                                      
                                                                                                                          - name: Commit and push changes
                                                                                                                                run: |
                                                                                                                                        git config --global user.email "github-actions[bot]@users.noreply.github.com"
                                                                                                                                                git config --global user.name "GitHub Actions Bot"
                                                                                                                                                        git add .env
                                                                                                                                                                git commit -m "Update Twilio credentials"
                                                                                                                                                                        git push
